### PR TITLE
Start the background task BEFORE the queue.join() to avoid deadlock.

### PR DESCRIPTION
**Pull request by ocschwar**
[This issue](https://github.com/invisibleroads/socketIO-client/issues/116) and [this one](https://github.com/miguelgrinberg/Flask-SocketIO/issues/255) appear to be addressed by this fix.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
What is the deadlock condition you are addressing with this change? How can I reproduce it?

**Comment by miguelgrinberg** [comment]
The writer task is not responsible for emptying the queue. At the time this code is executing, the client is using long-polling. The constant polls the client is doing will cause the queue to empty. The idea is that any remaining events generated from long-polling need to be processed before we switch to websocket.

**Comment by ocschwar** [comment]
Cutting and pasting from my flask-kitchen-sink server's views.py: 
`
@socketio.on_error_default
def default_error_handler(e):
    app.logger.warning("Websocket ERROR")
    app.logger.warning(pprint.pformat(request.event))
    app.logger.warning(pprint.pformat(e))
    
@socketio.on('message')
def handle_message(*args):
    print('received message: ' , args)
    emit('message', {'data': 'Handled','msg':args})
        
@socketio.on('project')
def handle_project(message):
    msg=message['data']
    ID = msg['id']
    client = msg['client']
    if app.etaggery.get(ID) == msg['etag']:
        # up to date. Wait here.
        emit("message",{"test":"test"})
        if ID in app.waiting:
            e = app.evts[ID]
        else:
            e = event.Event()
            app.evts[ID]=e
            app.waiting.add(ID)
        e.wait()
    emit('project', {"action":"reload"})
    app.logger.info("RELOAD SENT %s "%client)

@socketio.on('connect', namespace='/')
def test_connect():
    print ("CONNECT")

@socketio.on('disconnect', namespace='/')
def test_disconnect():
    print('Client disconnected')    
`

And the socketIO-client : 

`
#!/usr/bin/python
import sys
from socketIO_client import SocketIO, LoggingNamespace, BaseNamespace
import time
import requests
#import websocket
import ssl
import json
from argparse import ArgumentParser
import logging.handlers
logging.getLogger('requests').setLevel(logging.WARNING)
logging.basicConfig(level=logging.WARNING)

usage = """
"""


def main(args):
    def callback(*args):
        print("CB",args)

    def on_project(*args):
        print("PROJ",args)
        if args[0]['action'] == "reload":
            socketIO.disconnect()
    def on_response(*args):
        print("RESP",args)

    def on_error(*args):
        print("ERROR",args)


    parser = ArgumentParser( usage=usage, )
    parser.add_argument( "--password",
                       action="store",
                       dest="password",
                       help="Use this password" )
    parser.add_argument( "--port",
                       action="store",type=int,
                       dest="port", default=5000,
                       help="Specify port number for SSL service. " )
    parser.add_argument( "--wait",
                       action="store",type=int,
                       dest="wait", default=None,
                       help="waiting " )
    parser.add_argument( "project",
                       action="store",type=int,
                       default=1,
                       help="project ID. " )
    parser.add_argument( "--base-url",default='https://localhost',
                       action="store",
                       dest="baseurl",
                       help="baseurl" )
    parser.add_argument( "--username",
                       action="store",
                       dest="username",
                       help="Use this password" )
    opts = parser.parse_args()
    r = requests.get('%s:%s/project/%s'%(opts.baseurl,opts.port,opts.project), 
                     auth=requests.auth.HTTPBasicAuth(opts.username,opts.password),
                     headers={"accept":"application/json"})                     
    j = json.loads(r.content.decode())
    etag = r.headers['Etag']
    print((etag,opts.project))
    print("LOWLEVEL")

    socketIO = SocketIO(opts.baseurl, opts.port,
                        namespace=LoggingNamespace,
                        ping_interval=10,pint_timeout=20,
                        hurry_interval_in_seconds=2)#,transports=['websocket'])
    print ("INIT", socketIO._url)
    logging.getLogger(socketIO._url).setLevel(logging.DEBUG)
   
    #    print ("connected")
    print(socketIO.on('project', on_project))
    print(socketIO.on('message', on_response))
    socketIO.emit('project',{'data':{'client':'python','id':opts.project, 'etag':etag}})
    print (socketIO.wait(seconds=opts.wait))


if __name__ == '__main__':
    main(sys.argv)
`

I'll distill it to something smaller later in the day. 
I used print() debugging to see that the server never processes the first message, and just hangs out on the queue.join() with a single object in the queue that never gets flushed. The hang ends on the 60 second initial timeout. 

Meanwhile, my standard JS client functions properly.

**Comment by ocschwar** [comment]
[reproduce.tar.gz](https://github.com/miguelgrinberg/python-engineio/files/253420/reproduce.tar.gz)

Here we go.

**Comment by miguelgrinberg** [comment]
This appears to be an outdated issue, since I can't reproduce the problem with the project provided. Please reopen if the issue persists on your side.

**Pull request closed without merging**
